name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Rust
        uses: https://enduringtech.dev/actions/setup-rust-action@1780873c7b576612439a134613cc4cc74ce5538c # v1
        with:
          target: wasm32-unknown-unknown
      - name: Set up Trunk
        run: cargo install trunk

      - name: Build
        run: trunk build --release

      - name: Upload artifacts
        uses: https://enduringtech.dev/actions/upload-artifact-action@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: docker
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout
        uses: https://enduringtech.dev/actions/checkout-action@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up git
        run: |
          git config user.email forge.svc@enduringtech.dev
          git config user.name forge[bot]

      - name: Set up pages branch
        run: git switch --orphan pages

      - name: Download artifacts
        uses: https://enduringtech.dev/actions/download-artifact-action@d8d0a99033603453ad2255e58720b460a0555e1e # v4
        with:
          name: dist

      - name: Deploy artifacts
        run: |
          git add .
          git commit -m deployment --author "${{ github.actor }} <${{ github.actor }}@noreply.enduringtech.dev>"
          git push --force --set-upstream origin pages